//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK_Paper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_GK_Quetion_BankEntities1 : DbContext
    {
        public db_GK_Quetion_BankEntities1()
            : base("name=db_GK_Quetion_BankEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Chapter_Name> Tbl_Chapter_Name { get; set; }
        public virtual DbSet<tbl_Question_Add> tbl_Question_Add { get; set; }
        public virtual DbSet<Tbl_gklogin> Tbl_gklogin { get; set; }
        public virtual DbSet<Tbl_gk_question_list> Tbl_gk_question_list { get; set; }
        public virtual DbSet<tbl_Question_Paper> tbl_Question_Paper { get; set; }
        public virtual DbSet<Tbl_Final_Que> Tbl_Final_Que { get; set; }
    }
}
