//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK_Paper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Question_Add
    {
        public int id { get; set; }
        public string Chapter_Name { get; set; }
        public string Question_Type { get; set; }
        public string Question_Name { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Ans1 { get; set; }
        public string Ans2 { get; set; }
        public string Ans3 { get; set; }
        public string Ans4 { get; set; }
        public string Correct_Option { get; set; }
        public string Verify { get; set; }
    }
}
