//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK_Paper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Chapter_Name
    {
        public int Id { get; set; }
        public string Chapter_Name { get; set; }
        public string Active { get; set; }
    }
}
