//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK_Paper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_gklogin
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email_ID { get; set; }
        public string Mobile_no { get; set; }
        public string Password { get; set; }
        public string Inedx_no { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string IP_Adress { get; set; }
        public string adhar_no { get; set; }
    }
}
