//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK_Paper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_gk_question_list
    {
        public int ID { get; set; }
        public string Sr_no { get; set; }
        public string check_list { get; set; }
        public string questions_list { get; set; }
        public string options { get; set; }
    }
}
