//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK_Paper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Final_Que
    {
        public int id { get; set; }
        public string Index_No { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string IP_Address { get; set; }
        public string Type { get; set; }
        public string Question_Id { get; set; }
        public string Paper_ID { get; set; }
        public string Question { get; set; }
        public string Option_A { get; set; }
        public string Option_B { get; set; }
        public string Option_C { get; set; }
        public string Option_D { get; set; }
        public string Option_1 { get; set; }
        public string Option_2 { get; set; }
        public string Option_3 { get; set; }
        public string Option_4 { get; set; }
        public string Correct_Option { get; set; }
        public string Verify { get; set; }
    }
}
